// Ports Nova's SVG template from the design handoff into TypeScript.
//
//   node scripts/port-avatar.mjs
//
// Reads design/quest-board/screens/Avatar.dc.html, takes the <svg>…</svg> template and
// converts its little templating language to a template-literal function:
//   <sc-if value="{{flag}}">…</sc-if>  →  ${v.flag ? `…` : ''}
//   {{name}}                           →  ${v.name}
// The values themselves are computed in src/avatar.ts (the port of renderVals()).
// scripts/rig.mjs then adds the animation joints (elbows, waist) the emotes need.
// Re-run this whenever the design's Avatar.dc.html changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { rig } from './rig.mjs';

const SRC = new URL('../design/quest-board/screens/Avatar.dc.html', import.meta.url);
const OUT = new URL('../src/avatarSvg.gen.ts', import.meta.url);

const html = readFileSync(SRC, 'utf8');
const start = html.indexOf('<svg ');
const end = html.indexOf('</svg>', start);
if (start < 0 || end < 0) throw new Error('No <svg> template found');
let svg = html.slice(start, end + '</svg>'.length);

// Drop comments and collapse the indentation (keeps the output compact).
svg = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/\n\s*/g, '\n').trim();
// The outer size becomes a parameter so callers can draw her at any scale.
svg = svg.replace('<svg width="200" height="300"', '<svg width="{{w}}" height="{{h}}" class="nova"');
// Elbows, a waist joint and front-of-body arms for the emotes (scripts/rig.mjs).
svg = rig(svg);

const vars = new Set();
const esc = (text) =>
  text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
    .replace(/\{\{([a-zA-Z0-9_]+)\}\}/g, (_, name) => {
      vars.add(name);
      return '${v.' + name + '}';
    });

// Stack-based conversion of (possibly nested) <sc-if> blocks.
const token = /<sc-if value="\{\{([a-zA-Z0-9_]+)\}\}"[^>]*>|<\/sc-if>/g;
const stack = [{ name: null, buf: '' }];
let last = 0;
let m;
let blocks = 0;
while ((m = token.exec(svg))) {
  stack[stack.length - 1].buf += esc(svg.slice(last, m.index));
  last = token.lastIndex;
  if (m[1]) {
    vars.add(m[1]);
    stack.push({ name: m[1], buf: '' });
    blocks++;
  } else {
    const done = stack.pop();
    if (!done || done.name === null) throw new Error('Unbalanced </sc-if>');
    stack[stack.length - 1].buf += '${v.' + done.name + " ? `" + done.buf + "` : ''}";
  }
}
stack[0].buf += esc(svg.slice(last));
if (stack.length !== 1) throw new Error('Unclosed <sc-if>');

const names = [...vars].sort();
const out = `// GENERATED by scripts/port-avatar.mjs from design/quest-board/screens/Avatar.dc.html (+ scripts/rig.mjs).
// Do not edit by hand: change the design file and re-run \`node scripts/port-avatar.mjs\`.
// ${blocks} conditional layers, ${names.length} values. Values are computed in avatar.ts.

export type AvatarVals = Record<(typeof AVATAR_VARS)[number], string | number | boolean>;

export const AVATAR_VARS = ${JSON.stringify(names)} as const;

export function renderAvatarSvg(v: AvatarVals): string {
  return \`${stack[0].buf}\`;
}
`;
writeFileSync(OUT, out);
console.log(`wrote ${OUT.pathname}: ${blocks} conditional layers, ${names.length} values, ${(out.length / 1024).toFixed(1)} KB`);
